### ISSUE TITLE
`pip install -e .` fails with directory not found error

### ISSUE THREAD

**Issue by BenWibking** [mikegrudic/meshoid#1]
Hi,

Running `pip install -e .` inside the root directory results in an error. Changing the line in `setup.py` from

`packages=['Meshoid'],`
to
`packages=['meshoid'],`

however, fixes the error.

**Comment by mikegrudic** [comment]
Thanks Ben, I've just pushed a fix and checked that pip install -e works. Let me know if there are any issues.
